
["云南朗坤"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["兰州"]
mk = true
file = "mdb"
tip = "异型卡需要提供两个"

["兰州工作证"]
mk = false
file = "xlsx"
tip = "兰州工作证不需要MK文件"

["南通地铁"]
mk = false
file = "mdb"
tip = "具体格式要求见生产通知单"

["合肥通"]
mk = true
file = "mdb"
tip = "当前地区无注意事项"

["呼和浩特"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["哈尔滨城市通"]
mk = false
file = "mdb"
tip = "当前地区无注意事项"

["哈尔滨学院"]
mk = false
file = "mdb"
tip = "注意芯片厂商"

["国网技术学院"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["天津"]
mk = true
file = "mdb"
tip = "当前地区无注意事项"

["山西医科大学"]
mk = false
file = "mdb"
tip = "当前地区无注意事项"

["平凉公交"]
mk = false
file = "mdb"
tip = "当前地区无注意事项"

["广水"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["徐州地铁"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["抚顺"]
mk = false
file = "mdb"
tip = "当前地区无注意事项"

["昆明"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["柳州公交"]
mk = true
file = "xlsx"
tip = "当前地区无注意事项"

["桂林公交"]
mk = false
file = "mdb"
tip = "当前地区无注意事项"

["江苏乾翔"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["泸州公交"]
mk = false
file = "mdb"
tip = "根据卡类型进行制作，特别注意老年卡和普通卡"

["洪城"]
mk = false
file = "mdb"
tip = "备卡要分开提供"

["济南地铁 UL"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["淄博公交"]
mk = false
file = "mdb"
tip = "分为开通和不开通两种类型"

["淄博血站不开通"]
mk = false
file = "xlsx"
tip = "开通的类型使用淄博公交的逻辑即可"

["淮北"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["滨州公交"]
mk = false
file = "mdb"
tip = "处理逻辑跟芯片类型有关"

["漯河"]
mk = false
file = "mdb"
tip = "当前地区无注意事项"

["潍坊"]
mk = false
file = "mdb"
tip = "需要手动修改序号"

["琴岛通"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["琴岛通1280"]
mk = true
file = "xlsx"
tip = "当前地区无注意事项"

["盐城"]
mk = false
file = "mdb"
tip = "当前地区无注意事项"

["盱眙"]
mk = false
file = "mdb"
tip = "当前地区无注意事项"

["石家庄"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["穆棱"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["上海数维"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["第一医科大学"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["西安交通大学"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["西安文理学院"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["西藏拉萨"]
mk = false
file = "mdb"
tip = "请注意根据制卡数据修改启用标识"

["西藏林芝"]
mk = false
file = "mdb"
tip = "当前地区无注意事项"

["运城盐湖王府学校"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["邹平"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["郴州"]
mk = true
file = "mdb"
tip = "当前地区无注意事项"

["重庆"]
mk = false
file = "mdb"
tip = "目前默认支持的是331-A1，遇到其他芯片类型则需要修改"

["长沙公交"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["陕西师范大学"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["随州"]
mk = false
file = "mdb"
tip = "当前地区无注意事项"

["青岛博研加气站"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["青岛理工大学"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["洛阳"]
mk = false
file = "mdb"
tip = "当前地区无注意事项"

["新开普"]
mk = false
file = "xlsx"
tip = "当前地区无注意事项"

["济南员工卡"]
mk = false
file = "mdb"
tip = "当前地区无注意事项"
